<h2 style="color:green" align="center">Implement Neural Network (or Logistic Regression) From Scratch</h2>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],
                                                    df.bought_insurance,
                                                    test_size=0.2)

In [4]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

<img src="nn.jpg" height=800 width=800/>

In [5]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,),
                       activation='sigmoid',
                       kernel_initializer='ones',
                       bias_initializer='zeros')
])
model

In [6]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model

In [7]:
model.fit(X_train_scaled, y_train, epochs=500)#5000

Epoch 1/500
1/1 [==============================] - 1s 694ms/step - loss: 0.7229 - accuracy: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7224 - accuracy: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7220 - accuracy: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7216 - accuracy: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7212 - accuracy: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7207 - accuracy: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7203 - accuracy: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7199 - accuracy: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7195 - accuracy: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7191 - accuracy: 0.5000
Epoch 11/500
1/1 [=========

1/1 [==============================] - 0s 5ms/step - loss: 0.6911 - accuracy: 0.5000
Epoch 85/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6908 - accuracy: 0.5000
Epoch 86/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6904 - accuracy: 0.5000
Epoch 87/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6901 - accuracy: 0.5000
Epoch 88/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6898 - accuracy: 0.5000
Epoch 89/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6894 - accuracy: 0.5000
Epoch 90/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6891 - accuracy: 0.5000
Epoch 91/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6888 - accuracy: 0.5000
Epoch 92/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6885 - accuracy: 0.5000
Epoch 93/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6881 - accuracy: 0.5000
Epoch 94/500
1/1 [===============

Epoch 167/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6671 - accuracy: 0.5000
Epoch 168/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6668 - accuracy: 0.5000
Epoch 169/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6666 - accuracy: 0.5000
Epoch 170/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6663 - accuracy: 0.5000
Epoch 171/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6661 - accuracy: 0.5000
Epoch 172/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6658 - accuracy: 0.5000
Epoch 173/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6656 - accuracy: 0.5455
Epoch 174/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6654 - accuracy: 0.5455
Epoch 175/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6651 - accuracy: 0.5455
Epoch 176/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6649 - accuracy: 0.5455
Epoch 177/

1/1 [==============================] - 0s 7ms/step - loss: 0.6500 - accuracy: 0.6364
Epoch 250/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6498 - accuracy: 0.6364
Epoch 251/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6496 - accuracy: 0.6364
Epoch 252/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6495 - accuracy: 0.6364
Epoch 253/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6493 - accuracy: 0.6364
Epoch 254/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6491 - accuracy: 0.6364
Epoch 255/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6489 - accuracy: 0.6364
Epoch 256/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6488 - accuracy: 0.6364
Epoch 257/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6486 - accuracy: 0.6364
Epoch 258/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6484 - accuracy: 0.6364
Epoch 259/500
1/1 [=====

1/1 [==============================] - 0s 7ms/step - loss: 0.6381 - accuracy: 0.6364
Epoch 332/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6379 - accuracy: 0.6364
Epoch 333/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6378 - accuracy: 0.6364
Epoch 334/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6377 - accuracy: 0.6364
Epoch 335/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6376 - accuracy: 0.6364
Epoch 336/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6375 - accuracy: 0.6364
Epoch 337/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6373 - accuracy: 0.6364
Epoch 338/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6372 - accuracy: 0.6364
Epoch 339/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6371 - accuracy: 0.6364
Epoch 340/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6370 - accuracy: 0.6364
Epoch 341/500
1/1 [====

1/1 [==============================] - 0s 5ms/step - loss: 0.6297 - accuracy: 0.6364
Epoch 414/500
1/1 [==============================] - 0s 9ms/step - loss: 0.6296 - accuracy: 0.6364
Epoch 415/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6295 - accuracy: 0.6364
Epoch 416/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6294 - accuracy: 0.6364
Epoch 417/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6293 - accuracy: 0.6364
Epoch 418/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6292 - accuracy: 0.6364
Epoch 419/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6292 - accuracy: 0.6364
Epoch 420/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6291 - accuracy: 0.6364
Epoch 421/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6290 - accuracy: 0.6364
Epoch 422/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6289 - accuracy: 0.6364
Epoch 423/500
1/1 [====

1/1 [==============================] - 0s 10ms/step - loss: 0.6234 - accuracy: 0.6364
Epoch 496/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6233 - accuracy: 0.6364
Epoch 497/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6232 - accuracy: 0.6364
Epoch 498/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6232 - accuracy: 0.6364
Epoch 499/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6231 - accuracy: 0.6364
Epoch 500/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6230 - accuracy: 0.6364


In [8]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 149ms/step - loss: 0.6255 - accuracy: 0.6667


[0.6254934072494507, 0.6666666865348816]

In [9]:
y_pred=model.predict(X_test_scaled)
y_pred

1/1 [==============================] - 0s 98ms/step


array([[0.44910318],
       [0.45695528],
       [0.44910318],
       [0.6826653 ],
       [0.6757611 ],
       [0.6216819 ]], dtype=float32)

In [10]:
coef, intercept = model.get_weights()

In [11]:
coef, intercept

(array([[0.79221886],
        [0.67722154]], dtype=float32),
 array([-0.4023496], dtype=float32))

**Instead of model.predict, write our own prediction function that uses w1,w2 and bias**

In [14]:
def mysigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))

In [15]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return mysigmoid(weighted_sum)

In [16]:
prediction_function(18, 1)

0.9999995129073603

In [17]:
if prediction_function(18,1) >=0.5:
    print(1)
else:
    print(0)

1


# :: Manual ANN Code ::

In [18]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

In [20]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [21]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2,self.bias =self.gradient_descent(X['age'],
                                         X['affordibility'],
                                         y,epochs, loss_thresold)
        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2},bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] +\
              self.w2*X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs,loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),
                               (y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),
                               (y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'% i Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias},loss:{loss}')
            
            if loss<=loss_thresold:
                print (f'loss Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [22]:
customModel = myNN()
customModel

In [23]:
vvv=800#8000
customModel.fit(X_train_scaled, y_train, epochs=vvv, loss_thresold=0.4631)

% i Epoch:0, w1:0.9746936884392039, w2:0.9355414162805802, bias:-0.12323191277535987,loss:0.7228670678688007
% i Epoch:50, w1:1.6292731150228381, w2:1.1572401152686178, bias:-1.396451984775074,loss:0.5434024749171878
% i Epoch:100, w1:2.457501433729953, w2:1.4566780781012862, bias:-1.9847007295376597,loss:0.49812714209428405
% i Epoch:150, w1:3.2401539898124248, w2:1.6353301948732637, bias:-2.4542133976249048,loss:0.46335874949859907
loss Epoch:151, w1:3.2552495926473672, w2:1.6382100539944409, bias:-2.462793872577338, loss:0.46273726629051504
Final weights and bias: w1: 3.2552495926473672, w2: 1.6382100539944409,bias: -2.462793872577338


In [24]:
customModel.w1,customModel.w2,customModel.bias

(3.2552495926473672, 1.6382100539944409, -2.462793872577338)

In [25]:
customModel.predict(X_test_scaled)

16    0.161247
13    0.179642
1     0.161247
8     0.767397
17    0.743351
11    0.521708
dtype: float64