<div>
    <img src="../assets/1_header.png">
</div>

# 1. What is Tensorflow ? 
<div>
    <img src="../assets/9_what_is_tensorflow.png">
</div>

# 2. What is Tensor ?? 
- In TensorFlow, a tensor is a multi-dimensional array that represents the fundamental data structure used for computations.
Here's a breakdown of its key aspects:

1. Multi-dimensional array:
Think of a tensor as a generalization of vectors and matrices to higher dimensions. A scalar is a 0-dimensional tensor, a vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor, and so on.

3. Data type:
Tensors have a uniform data type (e.g., float32, int64), which specifies the type of values stored within the tensor.


5. Immutable:
Tensors are immutable, meaning that their contents cannot be modified once created. Instead, operations on tensors create new tensors.


7. Flow of data:
The name "TensorFlow" reflects the flow of tensors through a computational graph. Tensors are passed between nodes in the graph, representing the input and output of operations.


9. Analogy: You can think of tensors as containers that hold data, similar to NumPy arrays. However, tensors offer additional functionalities for efficient computation on GPUs and distributed systems, making them suitable for large-scale machine learning tasks.

<div>
    <img src="../assets/10_tensor.png">
</div>

# 3. Introduction of Tensorflow

In [3]:
# import TensorFlow 
import tensorflow as tf 
print(tf.__version__)

2.17.0


In [4]:
# create tensors with tf.contant() 
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check the number of dimension of a tensor (ndim stands for  no. of dimension)
scalar.ndim

0

In [6]:
# create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
# check the number of dimension of a vector
vector.ndim

1

In [8]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
matrix.ndim

2

In [10]:
# create another matrix 
another_matrix = tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]], dtype=tf.float16) 
#specify the data type  with dtype parameters.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
# What's the number of dimensions of another_matrix 
another_matrix.ndim

2

In [12]:
# Let's create a tensor 
tensor =tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                     [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [13]:
tensor.ndim

3

### What we've create so far:
* Scalar: a single number 
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of number.
* Tensor: is a n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a1-dimensional)

# 4. Creating tensors with `tf.tensor`

In [16]:
# create the same tensor with tf.variable() as above 
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [17]:
# Let's try change one of the elements in our changeable_tensor 
changeable_tensor[0] = 7 
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [58]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [19]:
# Let's try change our unchangeable_tensor 
# It will probabily through an error.
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

<p style="color:red; font-size:26px;">Note:</p>

-  Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as Tensorflow does this for you however, if in doubt use tf.constant and tf.Variable change it later if needed.

# 5. Creating random tensor
    Random Tensors are tensor of some abitrary size which contain random numbers.

<div>
    <img src="../assets/11_random_tensor.png">
</div>

In [36]:
import tensorflow as tf

# Create a random tensor of shape (3, 4) with values between 0 and 1
random_tensor_tf = tf.random.uniform(shape=(3,4)) 
'''Uniform distribution: is sometime also known as a rectangualar 
distribution  is a distribution that as constant probability'''

# Create a random tensor with specific min and max values
random_tensor_tf_custom = tf.random.uniform(shape=(3,4),minval=-2.0, maxval=1.0)

# printing of tensors 
print("Random Tensor (0 to 1)",random_tensor_tf,"\n")
print("Random Tensor (-2 to 1)",random_tensor_tf_custom)

Random Tensor (0 to 1) tf.Tensor(
[[0.88814485 0.3834145  0.74727833 0.81971943]
 [0.96516395 0.09472287 0.8395599  0.82604504]
 [0.78410304 0.25773227 0.91055346 0.4522406 ]], shape=(3, 4), dtype=float32) 

Random Tensor (-2 to 1) tf.Tensor(
[[-0.75589526  0.4487145  -1.0732496   0.13314629]
 [-0.2119801  -1.0183179   0.85736585 -1.722616  ]
 [-1.5763515  -1.1842179   0.8230462  -1.054286  ]], shape=(3, 4), dtype=float32)


In [60]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility 
random_1 = random_1.normal(shape=(3,2)) 
'''Normal Distribution is the most common or normal form of distribution
of Random Variables, hence the name “normal distribution.” 
It is also called Gaussian Distribution in Statistics or Probability.'''

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal ? 
print(random_1== random_2)

# Yes they are because of the seed number.

tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


In [54]:
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [62]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility 
random_1 = random_1.normal(shape=(3,2)) 
'''Normal Distribution is the most common or normal form of distribution
of Random Variables, hence the name “normal distribution.” 
It is also called Gaussian Distribution in Statistics or Probability.'''

random_2 = tf.random.Generator.from_seed(43)
random_2 = random_2.normal(shape=(3,2))

# Are they equal ? 
print(random_1== random_2)

# No, they aren't equal

tf.Tensor(
[[False False]
 [False False]
 [False False]], shape=(3, 2), dtype=bool)


In [58]:
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>)

# 6. Shuffle the order of elements in a tensor

-  Syntax
  
`tf.random.shuffle(value, seed=None, name=None)`

1. value: A Tensor to be shuffled.
2. seed: A Python integer. Used to create a random seed for the distribution. See tf.random.set_seed for behavior.
4. name: A name for the operation (optional).

In [21]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffle =  tf.constant([[10,7],[3,4],[2,5]])
not_shuffle.ndim

2

In [23]:
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [54]:
# shuffle our not_shuffle tensor 
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [72]:
# still getting different tensor 
tf.random.shuffle(not_shuffle,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

-  It lookslike if we want our shuffled tensors to be the same order , we've got to use the global level random seed as well as the operation level reandom seed: 

    - **Rule:** If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [117]:
tf.random.set_seed(42) # global level random seed 
tf.random.shuffle(not_shuffle,seed=42) # operational level random seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

🧷 **Exercise** Create tensor and shuffle it randomly also assign random seed to it for reproducability. 

In [122]:
tensor = tf.constant([[10,7],
                      [3,4],
                      [2,5]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [113]:
tensor.ndim

2

In [115]:
shuffle_tensor = tf.random.shuffle(tensor,seed=42)
shuffle_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

# 7. Other ways to make tensors
- `tf.ones()` and `tf.zeros()`

In [133]:
# Create tensor with all ones
one = tf.ones([5,5]) # 5 rows and 5 columns
one

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [143]:
# another way to create the same thing
one = tf.ones(shape=(3,3)) # 3 rows and 3 columns
one

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [135]:
# Creating tensor with all zeros
zero = tf.zeros([5,5])
zero

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [149]:
# same tensor with different parameter
zero = tf.zeros(shape=(5,5))
zero

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# 8. Turn Numpy array into Tensors 
- `tf.constant` and `tf.convert_to_tensor`
- The main difference between Numpy arrays are TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [166]:
# You can also turn NumPy array into tensors 
import numpy as np 
numpy_A = np.arange(1,25,dtype=int) # creating numpy array from 1 to 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [172]:
# First Method 
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [174]:
# now i want to change the shape of it 
A = tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [188]:
A.ndim

3

In [179]:
# Second Method 
B = tf.convert_to_tensor(numpy_A)
B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [186]:
B.ndim

1

# 9. Getting Information from our tensors
-  When dealing with tensors you probably want to be aware of the following attributes; 

- Tensor Attributes
    * Shape
    * Rank
    * Axis and dimension
    * Size

<div>
    <img src="../assets/12_tensor_attributes.png">
</div>

In [239]:
# create a rank 4 tensor(4 dimension) 
rank_4_tensor = np.arange(81).reshape(3, 3, 3, 3)
rank_4_tensor

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [241]:
rank_4_tensor[0]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [243]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

((3, 3, 3, 3), 4, <tf.Tensor: shape=(), dtype=int32, numpy=81>)

In [247]:
3*3*3*3

81

In [249]:
# Get various aAttribute of our tensors 
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimension:",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along with 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor))
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: int32
Number of dimension: 4
Shape of tensor: (3, 3, 3, 3)
Elements along with 0 axis: 3
Elements along the last axis: 3
Total number of elements in our tensor: tf.Tensor(81, shape=(), dtype=int32)
Total number of elements in our tensor: 81


# 10. Indexing Tensors 
- Tensors can be indexed just like the python list


In [252]:
# Get the first 2 elements of each dimension 
rank_4_tensor[:2,:2,:2,:2]

array([[[[ 0,  1],
         [ 3,  4]],

        [[ 9, 10],
         [12, 13]]],


       [[[27, 28],
         [30, 31]],

        [[36, 37],
         [39, 40]]]])

In [264]:
# Get the first element from each dimension from each index except for the final one 
rank_4_tensor[:1,:1,:1]

array([[[[0, 1, 2]]]])

In [320]:
# Get the first element from each dimension from each index except for the final one 
rank_4_tensor[0,:,0,0]

array([ 0,  9, 18])

In [256]:
# rank_4_tensor[0,0,0,:] 
# rank_4_tensor[:,0,:3,0]

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])