<div>
    <img src="../assets/1_header.png">
</div>

# 1. What is Tensorflow ? 
<div>
    <img src="../assets/9_what_is_tensorflow.png">
</div>

# 2. What is Tensor ?? 
- In TensorFlow, a tensor is a multi-dimensional array that represents the fundamental data structure used for computations.
Here's a breakdown of its key aspects:

1. Multi-dimensional array:
Think of a tensor as a generalization of vectors and matrices to higher dimensions. A scalar is a 0-dimensional tensor, a vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor, and so on.

3. Data type:
Tensors have a uniform data type (e.g., float32, int64), which specifies the type of values stored within the tensor.


5. Immutable:
Tensors are immutable, meaning that their contents cannot be modified once created. Instead, operations on tensors create new tensors.


7. Flow of data:
The name "TensorFlow" reflects the flow of tensors through a computational graph. Tensors are passed between nodes in the graph, representing the input and output of operations.


9. Analogy: You can think of tensors as containers that hold data, similar to NumPy arrays. However, tensors offer additional functionalities for efficient computation on GPUs and distributed systems, making them suitable for large-scale machine learning tasks.

<div>
    <img src="../assets/10_tensor.png">
</div>

# 3. Introduction of Tensorflow

In [2]:
# import TensorFlow 
import tensorflow as tf 
import numpy as np 
print(tf.__version__)

2.17.0


In [7]:
# create tensors with tf.contant() 
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
# check the number of dimension of a tensor (ndim stands for  no. of dimension)
scalar.ndim

0

In [9]:
# create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [10]:
# check the number of dimension of a vector
vector.ndim

1

In [11]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [12]:
matrix.ndim

2

In [13]:
# create another matrix 
another_matrix = tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]], dtype=tf.float16) 
#specify the data type  with dtype parameters.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
# What's the number of dimensions of another_matrix 
another_matrix.ndim

2

In [15]:
# Let's create a tensor 
tensor =tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                     [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [16]:
tensor.ndim

3

### What we've create so far:
* Scalar: a single number 
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of number.
* Tensor: is a n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a1-dimensional)

# 4. Creating tensors with `tf.tensor`

In [19]:
# create the same tensor with tf.variable() as above 
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [20]:
# Let's try change one of the elements in our changeable_tensor 
changeable_tensor[0] = 7 
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [56]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [58]:
# Let's try change our unchangeable_tensor 
# It will probabily through an error.
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

<p style="color:red; font-size:26px;">Note:</p>

-  Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as Tensorflow does this for you however, if in doubt use tf.constant and tf.Variable change it later if needed.

# 5. Creating random tensor
    Random Tensors are tensor of some abitrary size which contain random numbers.

<div>
    <img src="../assets/11_random_tensor.png">
</div>

In [62]:
import tensorflow as tf

# Create a random tensor of shape (3, 4) with values between 0 and 1
random_tensor_tf = tf.random.uniform(shape=(3,4)) 
'''Uniform distribution: is sometime also known as a rectangualar 
distribution  is a distribution that as constant probability'''

# Create a random tensor with specific min and max values
random_tensor_tf_custom = tf.random.uniform(shape=(3,4),minval=-2.0, maxval=1.0)

# printing of tensors 
print("Random Tensor (0 to 1)",random_tensor_tf,"\n")
print("Random Tensor (-2 to 1)",random_tensor_tf_custom)

Random Tensor (0 to 1) tf.Tensor(
[[0.94137645 0.50171494 0.7163639  0.924062  ]
 [0.7568463  0.68833673 0.9115056  0.11165595]
 [0.85399127 0.30261016 0.47248626 0.62748504]], shape=(3, 4), dtype=float32) 

Random Tensor (-2 to 1) tf.Tensor(
[[-1.361301   -1.913066   -0.94027066 -1.923625  ]
 [ 0.35482502 -0.5287225  -0.3919953  -0.91530824]
 [-0.7626215  -0.89712465 -0.11435986 -1.643062  ]], shape=(3, 4), dtype=float32)


In [64]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility 
random_1 = random_1.normal(shape=(3,2)) 
'''Normal Distribution is the most common or normal form of distribution
of Random Variables, hence the name “normal distribution.” 
It is also called Gaussian Distribution in Statistics or Probability.'''

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal ? 
print(random_1== random_2)

# Yes they are because of the seed number.

tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


In [65]:
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [67]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility 
random_1 = random_1.normal(shape=(3,2)) 
'''Normal Distribution is the most common or normal form of distribution
of Random Variables, hence the name “normal distribution.” 
It is also called Gaussian Distribution in Statistics or Probability.'''

random_2 = tf.random.Generator.from_seed(43)
random_2 = random_2.normal(shape=(3,2))

# Are they equal ? 
print(random_1== random_2)

# No, they aren't equal

tf.Tensor(
[[False False]
 [False False]
 [False False]], shape=(3, 2), dtype=bool)


In [69]:
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>)

# 6. Shuffle the order of elements in a tensor

-  Syntax
  
`tf.random.shuffle(value, seed=None, name=None)`

1. value: A Tensor to be shuffled.
2. seed: A Python integer. Used to create a random seed for the distribution. See tf.random.set_seed for behavior.
4. name: A name for the operation (optional).

In [74]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffle =  tf.constant([[10,7],[3,4],[2,5]])
not_shuffle.ndim

2

In [75]:
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [78]:
# shuffle our not_shuffle tensor 
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [80]:
# still getting different tensor 
tf.random.shuffle(not_shuffle,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

-  It lookslike if we want our shuffled tensors to be the same order , we've got to use the global level random seed as well as the operation level reandom seed: 

    - **Rule:** If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [83]:
tf.random.set_seed(42) # global level random seed 
tf.random.shuffle(not_shuffle,seed=42) # operational level random seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

🧷 **Exercise** Create tensor and shuffle it randomly also assign random seed to it for reproducability. 

In [86]:
tensor = tf.constant([[10,7],
                      [3,4],
                      [2,5]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [88]:
tensor.ndim

2

In [90]:
shuffle_tensor = tf.random.shuffle(tensor,seed=42)
shuffle_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

# 7. Other ways to make tensors
- `tf.ones()` and `tf.zeros()`

In [93]:
# Create tensor with all ones
one = tf.ones([5,5]) # 5 rows and 5 columns
one

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [95]:
# another way to create the same thing
one = tf.ones(shape=(3,3)) # 3 rows and 3 columns
one

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [97]:
# Creating tensor with all zeros
zero = tf.zeros([5,5])
zero

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [99]:
# same tensor with different parameter
zero = tf.zeros(shape=(5,5))
zero

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# 8. Turn Numpy array into Tensors 
- `tf.constant` and `tf.convert_to_tensor`
- The main difference between Numpy arrays are TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [102]:
# You can also turn NumPy array into tensors 
import numpy as np 
numpy_A = np.arange(1,25,dtype=int) # creating numpy array from 1 to 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [104]:
# First Method 
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [106]:
# now i want to change the shape of it 
A = tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [108]:
A.ndim

3

In [109]:
# Second Method 
B = tf.convert_to_tensor(numpy_A)
B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [112]:
B.ndim

1

# 9. Getting Information from our tensors
-  When dealing with tensors you probably want to be aware of the following attributes; 

- Tensor Attributes
    * Shape
    * Rank
    * Axis and dimension
    * Size

<div>
    <img src="../assets/12_tensor_attributes.png">
</div>

In [119]:
# create a rank 4 tensor(4 dimension) 
rank_4_tensor = np.arange(81).reshape(3, 3, 3, 3)
rank_4_tensor = tf.constant(rank_4_tensor)

In [121]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

In [123]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([3, 3, 3, 3]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=81>)

In [125]:
3*3*3*3

81

In [127]:
# Get various aAttribute of our tensors 
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimension:",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along with 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor))
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimension: 4
Shape of tensor: (3, 3, 3, 3)
Elements along with 0 axis: 3
Elements along the last axis: 3
Total number of elements in our tensor: tf.Tensor(81, shape=(), dtype=int32)
Total number of elements in our tensor: 81


# 10. Indexing Tensors 
- Tensors can be indexed just like the python list


In [129]:
# Get the first 2 elements of each dimension 
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 3,  4]],

        [[ 9, 10],
         [12, 13]]],


       [[[27, 28],
         [30, 31]],

        [[36, 37],
         [39, 40]]]])>

In [131]:
# Get the first element from each dimension from each index except for the final one 
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=int32, numpy=array([[[[0, 1, 2]]]])>

In [137]:
# Get the first element from sub-array of 1 element of 4 dimension  
rank_4_tensor[0,:,0,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 0,  9, 18])>

In [139]:
rank_4_tensor[0,0,0,:] 
# rank_4_tensor[:,0,:3,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2])>

In [141]:
# Create a rank 2 tensor (2 dimension) 
rank_2_tensor =  tf.constant([[1,2,3],
                              [4,5,6]])
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [143]:
rank_2_tensor.shape, tf.size(rank_2_tensor), rank_2_tensor.ndim

(TensorShape([2, 3]), <tf.Tensor: shape=(), dtype=int32, numpy=6>, 2)

In [149]:
# Get the last item of the each of row of our rank 2 tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6])>

# 11. Adding extra dimension to the tensor

In [154]:
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [160]:
rank_3_tensor = rank_2_tensor[:,: , tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

In [162]:
rank_3_tensor = rank_2_tensor[... , tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

In [168]:
# Alternative of the `tf.newaxis`
tf.expand_dims(rank_2_tensor,axis=-1)# -1 means expand the final axis 

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

In [172]:
tf.expand_dims(rank_2_tensor,axis=0) # expand the 0-axis 

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]])>

# 12. Manipulating Tensors (tensor operations)

## Basic Operations 
`+`, `-`, `*`, `/`

In [179]:
# You can add values to a tensor using the addition operator 
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [181]:
# Original tensor is unchanged 
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [183]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [185]:
# Substraction if you want 
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [187]:
# Now , lets not leave divide
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

## Built in `tf.math.<name>`

In [195]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [193]:
# Addition 
tf.math.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [199]:
# Subtraction 
tf.math.subtract(tensor,10) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [201]:
# Multiplication 
tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [203]:
# Division 
tf.math.divide(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

# 13. Matrix Multiplication 
`tf.linalg.matmul` or `tf.matmul`
- In machine learning, matrix multiplication is one of the most common tensor operations.
- There are two rules our tensors (or metrices) need to fulfil if we're going to matrix multiply them:
    1. The inner dimensions must match.
    2. The resulting matrix has the shape of the outter dimension.

In [235]:
# Matric multiplication in tensorflow 
print(tensor)
tf.matmul(tensor, tensor ) # basically performing dot product 

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [215]:
tensor, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [219]:
tensor * tensor # simply multipling the both tensors 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [221]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [7]:
# Create a tensror (3,2) tensor 
x = tf.constant([[1,2],[3,4],[5,6]])

# Create a tensror (3,2) tensor 
y = tf.constant([[7,8],[9,10],[11,12]])

In [229]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [233]:
# Try to matrix multiply tensor of same shape
tf.matmul(x,y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [242]:
# Let's change the shape of "y" 
y_changed = tf.reshape(y, shape=(2,3))
y_changed

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [244]:
# Again try to multiply y_changed to x
tf.matmul(x,y_changed)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [248]:
tf.matmul(tf.reshape(x,shape=(2,3)),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

## Transpose of matrix 

In [251]:
# can do the same with transpose 
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [255]:
# Try matrix multiplication with transpose rather than reshape 
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

## The dot product 
- Matrix multiplication is also referred to as the dot product.
- You can perform matrix multiplication using:
    - `tf.matmul()`
    - `tf.tensordot()`
    - `@`

In [19]:
# perform the dot product on x and y (requires x or y to be transpose)
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [27]:
# perform matrix multiplication between x and y (transpose) 
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [25]:
# perform matrix multiplication between x and y (reshape)
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [35]:
# Chekc the value of y, reshape y and transpose y 
print("Normal y:")
print(y,"\n") 

print("y reshape to (2,3):")
print(tf.reshape(y,(2,3)),"\n") 

print("y tranpose:")
print(tf.transpose(y))

Normal y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

y reshape to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

y tranpose:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


-  Generally, when performing matrix multipication on two tensors and one of the axes doesn't line up, you will transpose ()rather than reshape) one of the tensors to get satisify the matrix multiplication rules.

# 14. Changing the datatype of a tensor  

In [43]:
# Create a new tensor with default datatype(float 32)
b = tf.constant([1.2,3.2])
b.dtype

tf.float32

In [45]:
# Creating other tensor 
a = tf.constant([1,2,3,4])
a.dtype

tf.int32

In [47]:
# Change from float32  to float16 (reduce precision) 
d = tf.cast(b,dtype=tf.float16)
d, d.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3.2], dtype=float16)>,
 tf.float16)

In [53]:
# Change from int32 to float32 
e =  tf.cast(a,dtype=tf.float32)
e

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 4.], dtype=float32)>

# 15. Aggregating Tensors
- Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [7]:
# Get the absolute values 
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [9]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Let's go through the following form of aggregation 
* Get the minimum 
* Get the maximum 
* Get the mean of a tensor 
* Get the sum of tensor 

In [20]:
# Creating random tensor with values between 0 to 100 of size 50 
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([12, 53, 78, 89, 11, 42,  3, 29, 60, 30, 32, 19, 35, 52, 50,  3, 70,
       52,  4, 10, 95, 97, 32, 74, 77,  4, 12, 67, 90, 24, 47, 67, 83, 25,
        2,  2, 32, 57, 80, 18, 77, 63,  8, 89, 97, 16, 38, 13, 35, 28])>

In [22]:
tf.size(E), tf.shape(E), E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([50])>,
 1)

In [24]:
# Find the minimum 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [26]:
# Find the miximum 
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [28]:
# Find the mean 
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [30]:
# Find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2183>

## Exercise 

In [63]:
# find the varience 
import math
E = tf.constant(np.random.randint(0,100,size=50))
# we have to change the data type of E because the np.random 
# generates int but tf.math.reduce_std(E) accepts float number. 
E = tf.cast(E,dtype=tf.float32)

std_result = tf.math.reduce_std(E)
variance_result = tf.math.reduce_variance(E)

print("Standard Deviation:",std_result.numpy())
print("Variance:",variance_result.numpy())

Standard Deviation: 29.705732
Variance: 882.4305


# 16. Find the positional maximum and minimum  

In [5]:
# Create a new tensor for fiding positional maximum and minimum 
tf.random.set_seed(42) 
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [7]:
# Find the positional maximum 
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [9]:
# Index of largest value position 
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [11]:
# Find the max value of F 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [17]:
# Check for equality 
F[tf.argmax(F)]==tf.reduce_max(F) # True

<tf.Tensor: shape=(), dtype=bool, numpy=True>